#!/usr/bin/python

import json
import sys
import urllib2

sys.stdout.write('package commonmark\n')
sys.stdout.write('\n')
sys.stdout.write('// Autogenerated by scripts/generate_entities_go.py; do not edit.\n')
sys.stdout.write('var htmlEntities = map[string]string{\n')
data = urllib2.urlopen('https://html.spec.whatwg.org/multipage/entities.json').read()
json = json.loads(data)
for key, value in sorted(json.items(), key=lambda kv: kv[0].lower()):
    if not key.endswith(';'):
        continue
    key = key[1:-1]
    codepoints = value['codepoints']
    string_value = ''.join((unichr(codepoint) for codepoint in codepoints))
    if string_value == '\\':
        string_value = '\\\\'
    elif string_value == '\n':
        string_value = '\\n'
    elif string_value == '"':
        string_value = '\\"'
    line = u'\t"%s": "%s",\n' % (key, string_value)
    sys.stdout.write(line.encode('utf-8'))
sys.stdout.write('}\n')
